name: android-tests

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: macos-11
    env:
      JOB_BASE_NAME: macos-11-android-tests
    steps:
      - name: print labels
        run: echo "Hello!"

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck